name: Build and Push Latest

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SSL Certificates
        run: |
          echo "Installing SSL PFX for Integration Tests"
          sudo mkdir -p /usr/local/share/ca-certificates/extra
          sudo cp ./local-certs/emulator.pfx /usr/local/share/ca-certificates/extra/emulator.pfx
          sudo openssl pkcs12 -in ./local-certs/emulator.pfx -out emulator.pem -nodes
          sudo cp emulator.pem /usr/local/share/ca-certificates/extra/emulator.crt

          echo "Installing SSL CRT certificate for Integration Tests"
          sudo cp ./local-certs/emulator.crt /usr/local/share/ca-certificates/extra/emulator.crt

          # Update certificates
          sudo update-ca-certificates

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' # Adjust to your required .NET version

      - name: Run Integration Tests
        run: |
          dotnet test --verbosity minimal

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Extract Version
        id: get_version
        run: |
          VERSION=latest

      - name: Build Docker Image
        run: |
          docker build -t jamesgoulddev/azure-keyvault-emulator:latest .

      - name: Push Docker Image
        run: |
          docker push jamesgoulddev/azure-keyvault-emulator:latest
