name: Build and Push Dev Docker Image

on:
  pull_request:
    branches:
      - development  # Triggers when PRs are merged into "development"
    types:
      - closed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Integration Tests
      - run: dotnet test --verbosity minimal

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Extract Version
        id: get_version
        run: |
          VERSION=$(git describe --tags --always --dirty="-dev")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t jamesgoulddev/azure-keyvault-emulator:dev-${VERSION} .

      - name: Push Docker Image
        run: |
          docker push jamesgoulddev/azure-keyvault-emulator:dev-${VERSION}
